### ISSUE TITLE
Roots Thropy; Change `roots:bonfire` to `roots:pyre` in Triumph scripts

### ISSUE THREAD

**Issue by JadedMagic5** [Divine-Journey-2/main#187]
First check if this has been submitted before. If it already exists, please don't submit. Then check if you're on the latest Divine Journey 2 version. If not, please update first and see if the typo has been corrected. If not, fill out the form below by REWRITING the text below the titles, and delete this text as well.  
In addition to this report; in the last sentence above, replace "If not, " with "Lastly, "

**Running on Pack v2.1.1**

**The issue:**
Roots Trophy from Simple Trophies is spelt: _Roots Thropy_

**Location of item in game** (jei shows proper item name)
D:\Minecraft\Divine Journey 2\config\simple_trophies
{TrophyName:"**Roots Trophy**",TrophyVariant:"neon",TrophyItem:{id:"roots:bonfire",Count:1b,Damage:0s},TrophyColorRed:134,TrophyColorGreen:95,TrophyColorBlue:32}

**Location of where the issue comes from:**
D:\Minecraft\Divine Journey 2\config\triumph\functions\triumph\03_root_3

**Exact fix:**
While looking in the triumph functions change: (bold is the change)
give @p simple_trophies:trophy 1 0 {TrophyName:"**Roots Thropy**",TrophyVariant:"neon",TrophyItem:{id:"roots:bonfire",Count:1b,Damage:0s},TrophyColorRed:134,TrophyColorGreen:95,TrophyColorBlue:32}
to
give @p simple_trophies:trophy 1 0 {TrophyName:"**Roots Trophy**",TrophyVariant:"neon",TrophyItem:{id:"roots:bonfire",Count:1b,Damage:0s},TrophyColorRed:134,TrophyColorGreen:95,TrophyColorBlue:32}

Sorry for making my own format, this started as a typo fix, but then I found where the issue was, and kinda became more of a bug I guess?

**Comment by ZephyrWindSpirit** [comment]
Aww, thought it was a cool idea off of the word therapy.

**Comment by ToasterKoishi** [comment]
In my experience as a beta-tester spell-checker, usually most typos that look like puns are actually just typos lol (Atri pls don't hurt me)

**Comment by Atricos** [comment]
This was actually saved incorrectly in `simple_trophies.cfg` AND in the `truimph` folder. I fixed the former during the Beta, looks like I forgot to fix the latter though.

But it's fixed in 2.2.0 now! https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3449256

**Comment by NLBlacky** [comment]
![image](https://user-images.githubusercontent.com/42154364/132126856-f3960079-d71b-4f6e-a9f9-a1a9fb0c0e69.png)

I think something might still be messed up. I assume this has something to do with this issue report which is why I added this here.

**Comment by Atricos** [comment]
Oh, Roots renamed its Pyre into `roots:pyre` from `roots:bonfire` in 3.1. I'll have to fix that then.

**Comment by Atricos** [comment]
The Advancement should be working now, I changed `roots:bonfire` to `roots:pyre` in `config/triumph/script/triumph/dj2/03_root_3.txt`.

**Comment by Nagapito** [comment]
Seems you only changed the item detection but forgot to change the item icon so it still fails to load the Trophie....

**Comment by JohanniklasLp** [comment]
![grafik](https://user-images.githubusercontent.com/57828910/133324809-0ec4e204-a658-4c64-b508-fcaa4bd1ac12.png)
Can confirm (2.3.1)

**Comment by Nagapito** [comment]
Funny that, after I fix it on my client, the trophie now exists but it still does not have the Pyre. It shows as an empty trophie...
