### ISSUE TITLE
Add ability to turn off AE2 Channels

### ISSUE THREAD

**Issue by vishtheshnu** [Divine-Journey-2/main#248]
**Modpack version:**
2.2.0

**Describe the request:**
I would like the ability to disable AE2 channels in the configs without breaking recipes.

**Reasons why this should be added:**
AE2 channel management, especially for the large-scale automation required for this modpack, is incredibly tedious and takes away from the enjoyment of mid-late game automation. Having the ability to disable channels would make it easier to focus on the most fun aspects of Divine Journey 2 created by the developer.

**Describe alternatives you've considered:**
I considered the addition of Refined Storage, but that would take even more effort to balance and such new content mods won't be added.

**Additional context:**
Since disabling it also removes the AE2 Controller from the game, and many items require this as an ingredient, it would break the custom scripts. Creating a Contenttweaker item with the same recipe, using a conditional statement to check if the original exists and assigning the existing version to a variable, and using that variable in place of the <appliedenergistics2:controller> item throughout the script would be the easiest way to implement this. grep shows that there are 40 instances of <appliedenergistics2:controller> in the script files, so making such a change should hopefully not be too difficult.
If this request gets the greenlight, I could even look into implementing such a change myself and create a pull request :smile:

**Comment by WaitingIdly** [comment]
This would be best fixed by making disabled features in AE2 still register their blocks. This has already been requested of Trousers Edition. 
RS will never be added due to its significant performance problems in 1.12, particularly with large crafts.

**Comment by vishtheshnu** [comment]
> This would be best fixed by making disabled features in AE2 still register their blocks. This has already been requested of Trousers Edition.
> RS will never be added due to its significant performance problems in 1.12, particularly with large crafts.

It would be the easiest. Is there anything from the Trousers Edition devs about their willingness to add such a feature? And I don't expect RS to be added either.

**Comment by Waisse** [comment]
It's amazing that some people can tolerate very tedious recipes in an expert pack but still can't count to 8 and 32 for channels. Any modification to the pack is on you OP, it's laughable that you have considered changing configs, then adding another mod to replace AE2 rather than watching a tutorial on the feature that's traumatizing you so much you came here.

**Comment by vishtheshnu** [comment]
@Waisse dude, you don't have to be so rude about it. Even with an understanding of channels, many people would rather focus on the actual automation and features/changes of the pack itself rather than arranging a massive ME system for the nth time. The only reason I included RS in my post was because the template asked if I'd considered any alternatives, even though I know RS would be a terrible idea to add. And sure I could do it for myself, but I figured such an option would be nice to have for others who would also rather focus on what Divine Journey 2 itself brings to the table, so I posted this here.

**Comment by Waisse** [comment]
And many people would rather have those channels as they are part of ae2. They add some restriction to what you can do with the most broken inventory management/autocrafting mod in the modding sphere, that's a fair trade-off when all you have to do is plan your system a bit.
What's the alternative here? The option for on or off wouldn't make much sense. Why would a player willingly make it harder on himself? I was already surprised you could skip the Twilight Forest in DJ2 and not the several others, one note dimensions that were mandatory instead, so making channels optional would be even more baffling to me. It's such a minuscule part of the game in the grand scheme of things I don't understand why it should warrant more attention.
"many people would rather focus on the actual automation and features/changes of the pack itself rather than arranging a massive ME system". You are contradicting yourself.

**Comment by Atricos** [comment]
The pack isn't meant to be played this way. Refined Storage lags on larger setups, so it's not going to be added either.
